name: Code Linter

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        uses: wearerequired/lint-action@v1
        with:
          DEFAULT_BRANCH: main
          github_token: ${{ secrets.github_token }}
          #enable linters
          black: false